export enum ApiKeys {
    HttpClient = 'httpClient',
    AuthService = 'authService',
    UserService = 'userService',
    ProjectService = 'projectService',
    FileService = 'fileService',
    ComponentService = 'componentService',
    CodeGeneratorService = 'codeGeneratorService',
    FileExtensionsService = 'fileExtensionsService',
    ComponentPreset = 'componentPreset',
    ProjectType = 'projectType',
    FileType = 'fileType',
    ComponentFactory = 'componentFactory',
    ProjectState = 'projectState',
}